// Package topology turns oak-dev.yaml + component registry into concrete
// compose file chains, and writes the .generated/ artifacts that make the
// resulting setup inspectable: compose-args (the -f chain per stack, for
// `cat`-ing) and dev-live.yml (the merged live-mount overlay actually in
// effect). Everything under .generated/ is derived and gitignored - deleting
// the directory and re-running any oak-dev command regenerates it.
package topology

import (
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"oak-dev/internal/components"
	"oak-dev/internal/compose"
	"oak-dev/internal/config"
)

const genDir = ".generated"

// Render computes the effective compose files for every enabled stack and
// writes the .generated/ debug artifacts. It returns the per-stack file
// chains, keyed by stack name, ready to hand to compose.Run.
func Render(cfg *config.Config) (map[string][]string, error) {
	dir := filepath.Join(cfg.RepoRoot, genDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	if err := writeLibsOverlays(cfg); err != nil {
		return nil, err
	}

	files := map[string][]string{}
	var argsDump strings.Builder
	merged := map[string]any{"services": map[string]any{}}

	stacks := []struct {
		name string
		fn   func(*config.Config, map[string]bool) []string
	}{
		{components.StackRoot, compose.RootFiles},
		{components.StackCluster, compose.ClusterFiles},
		{components.StackWorker, compose.WorkerFiles},
	}

	for _, s := range stacks {
		if !cfg.StackEnabled(s.name) {
			continue
		}
		fchain := s.fn(cfg, cfg.Live)
		files[s.name] = fchain

		fmt.Fprintf(&argsDump, "# %s\n", s.name)
		for _, f := range fchain {
			fmt.Fprintf(&argsDump, "-f %s\n", f)
		}
		argsDump.WriteString("\n")

		for _, f := range fchain {
			if !strings.HasPrefix(filepath.Base(f), "override-live-") {
				continue
			}
			mergeFragment(merged, f)
		}
	}

	if err := os.WriteFile(filepath.Join(dir, "compose-args"), []byte(argsDump.String()), 0o644); err != nil {
		return nil, err
	}

	liveYAML, err := yaml.Marshal(merged)
	if err != nil {
		return nil, err
	}
	header := "# Generated by oak-dev - the union of every active compose/override-live-*.yml\n" +
		"# fragment plus any libs_repo mount. Informational only: oak-dev applies the\n" +
		"# individual fragment files directly, not this merged copy. Safe to delete.\n"
	if err := os.WriteFile(filepath.Join(dir, "dev-live.yml"), []byte(header+string(liveYAML)), 0o644); err != nil {
		return nil, err
	}

	return files, nil
}

func mergeFragment(merged map[string]any, path string) {
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var frag map[string]any
	if err := yaml.Unmarshal(data, &frag); err != nil {
		return
	}
	svcs, _ := frag["services"].(map[string]any)
	dst, _ := merged["services"].(map[string]any)
	maps.Copy(dst, svcs)
	merged["services"] = dst
}

// writeLibsOverlays generates .generated/libs-<stack>.yml when libs_repo is
// set: mounts the shared oakestra_utils_library over site-packages in every
// currently-live Python container in that stack (Phase 1d).
func writeLibsOverlays(cfg *config.Config) error {
	dir := filepath.Join(cfg.RepoRoot, genDir)
	for _, stack := range []string{components.StackRoot, components.StackCluster} {
		path := filepath.Join(dir, "libs-"+stack+".yml")
		if cfg.LibsRepo == "" {
			os.Remove(path)
			continue
		}
		svcs := map[string]any{}
		for _, c := range components.All() {
			if c.Kind != components.KindPython || !cfg.IsLive(c.Name) {
				continue
			}
			for _, t := range c.InStack(stack) {
				svcs[t.Container] = map[string]any{
					"volumes": []string{
						filepath.Join(cfg.LibsRepo, "oakestra_utils") +
							":/usr/local/lib/python3.10/site-packages/oakestra_utils:ro",
					},
				}
			}
		}
		if len(svcs) == 0 {
			os.Remove(path)
			continue
		}
		out := map[string]any{"services": svcs}
		data, err := yaml.Marshal(out)
		if err != nil {
			return err
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return err
		}
	}
	return nil
}
