// Package vscode generates .vscode/launch.json and .vscode/tasks.json from
// internal/components and the resolved config, and installs the result into
// any directory - this checkout, $OAKESTRA_REPO, $OAKESTRA_NET_REPO, or
// anywhere else an agent points `oak-dev vscode install` at.
//
// Every debugger port and source path oak-dev knows about already lives in
// internal/components and internal/config; this package's only job is
// rendering that into the two files VS Code reads, so the checked-in
// .vscode/launch.json this used to be a hand-maintained copy of can't drift
// from the registry again.
//
// oak-dev owns exactly the array elements whose "name" (launch.json) or
// "label"/"id" (tasks.json) starts with the prefix in launchPrefix/
// taskPrefix/inputPrefix - see generate.go. Everything else already in the
// file, generated by oak-dev in some earlier binary or hand-written by
// whoever opened the workspace, is left untouched and re-emitted as-is.
package vscode

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"oak-dev/internal/config"
)

// FileResult reports what Install did to one of the two files.
type FileResult struct {
	Path        string
	Changed     bool // content differs from what was on disk (written unless dryRun)
	HadComments bool // the file that was there had comments Install could not preserve
}

// Result is what Install did, one FileResult per file.
type Result struct {
	Launch FileResult
	Tasks  FileResult
}

// State classifies a directory against what the running binary would
// install there.
type State int

const (
	NotInstalled State = iota
	UpToDate
	Modified
)

func (s State) String() string {
	switch s {
	case NotInstalled:
		return "not installed"
	case UpToDate:
		return "up to date"
	case Modified:
		return "differs from this binary's config"
	default:
		return "unknown"
	}
}

func vscodeDir(targetDir string) string {
	return filepath.Join(targetDir, ".vscode")
}

// Install renders launch.json and tasks.json for targetDir and writes them,
// merging with whatever is already there (see the package doc). dryRun
// reports what would change without touching disk.
func Install(cfg *config.Config, targetDir string, dryRun bool) (Result, error) {
	targetDir, err := filepath.Abs(targetDir)
	if err != nil {
		return Result{}, err
	}
	g := generate(cfg, targetDir)
	dir := vscodeDir(targetDir)

	launchPath := filepath.Join(dir, "launch.json")
	launchDoc, launchHadComments, err := mergeLaunch(launchPath, g.launch)
	if err != nil {
		return Result{}, fmt.Errorf("merging %s: %w", launchPath, err)
	}
	launchChanged, err := writeIfChanged(launchPath, launchDoc, dryRun)
	if err != nil {
		return Result{}, err
	}

	tasksPath := filepath.Join(dir, "tasks.json")
	tasksDoc, tasksHadComments, err := mergeTasks(tasksPath, g.tasks, g.inputs)
	if err != nil {
		return Result{}, fmt.Errorf("merging %s: %w", tasksPath, err)
	}
	tasksChanged, err := writeIfChanged(tasksPath, tasksDoc, dryRun)
	if err != nil {
		return Result{}, err
	}

	return Result{
		Launch: FileResult{Path: launchPath, Changed: launchChanged, HadComments: launchHadComments},
		Tasks:  FileResult{Path: tasksPath, Changed: tasksChanged, HadComments: tasksHadComments},
	}, nil
}

// Status classifies targetDir: NotInstalled if neither file exists,
// Modified if installing now would change either one, UpToDate if neither
// would change.
func Status(cfg *config.Config, targetDir string) (State, error) {
	targetDir, err := filepath.Abs(targetDir)
	if err != nil {
		return NotInstalled, err
	}
	dir := vscodeDir(targetDir)
	launchExists := exists(filepath.Join(dir, "launch.json"))
	tasksExists := exists(filepath.Join(dir, "tasks.json"))
	if !launchExists && !tasksExists {
		return NotInstalled, nil
	}

	res, err := Install(cfg, targetDir, true)
	if err != nil {
		return NotInstalled, err
	}
	if res.Launch.Changed || res.Tasks.Changed {
		return Modified, nil
	}
	return UpToDate, nil
}

// UninstallFileResult reports what Uninstall did to one of the two files.
type UninstallFileResult struct {
	Path        string
	Found       bool // the file existed before Uninstall ran
	Removed     bool // deleted outright
	HadComments bool // the file had comments Uninstall could not preserve
}

// UninstallResult is what Uninstall did, one UninstallFileResult per file.
type UninstallResult struct {
	Launch UninstallFileResult
	Tasks  UninstallFileResult
}

// WouldDiscardComments reports, for each of launch.json/tasks.json in
// targetDir, whether it currently holds a comment beyond oak-dev's own
// generated header - the same signal Uninstall computes internally right
// before it rewrites or deletes each file. It exists so a caller (the
// `vscode uninstall` command) can ask for confirmation before Uninstall
// commits to that lossy rewrite, rather than only learning about the loss
// from Uninstall's result after it has already happened.
func WouldDiscardComments(targetDir string) (launch, tasks bool, err error) {
	targetDir, err = filepath.Abs(targetDir)
	if err != nil {
		return false, false, err
	}
	dir := vscodeDir(targetDir)
	if _, launch, err = readJSONMap(filepath.Join(dir, "launch.json"), launchHeader); err != nil {
		return false, false, err
	}
	if _, tasks, err = readJSONMap(filepath.Join(dir, "tasks.json"), tasksHeader); err != nil {
		return false, false, err
	}
	return launch, tasks, nil
}

// Uninstall removes oak-dev's own entries from launch.json and tasks.json,
// deleting either file outright once nothing but the bare version/array
// skeleton oak-dev itself would have written is left in it. Foreign entries -
// anything without the ownership prefix - are always preserved, but comments
// are not: the merge pipeline parses through encoding/json, which has no
// concept of them. A file whose only foreign content was a comment is never
// deleted outright for that reason - see uninstallLaunch/uninstallTasks -
// but any comment attached to a surviving foreign entry is still lost, which
// is why HadComments is reported for the caller to warn about either way.
func Uninstall(targetDir string) (UninstallResult, error) {
	targetDir, err := filepath.Abs(targetDir)
	if err != nil {
		return UninstallResult{}, err
	}
	dir := vscodeDir(targetDir)
	launch, err := uninstallLaunch(filepath.Join(dir, "launch.json"))
	if err != nil {
		return UninstallResult{}, err
	}
	tasks, err := uninstallTasks(filepath.Join(dir, "tasks.json"))
	if err != nil {
		return UninstallResult{}, err
	}
	return UninstallResult{Launch: launch, Tasks: tasks}, nil
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// writeIfChanged writes data to path when it differs from what's already
// there (or the file doesn't exist yet), reporting whether it did - or would
// have, under dryRun, when nothing is actually touched.
func writeIfChanged(path string, data []byte, dryRun bool) (bool, error) {
	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
		if bytes.Equal(existing, data) {
			return false, nil
		}
	case os.IsNotExist(err):
		// No existing file - unconditionally a change.
	default:
		return false, err
	}
	if dryRun {
		return true, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	return true, os.WriteFile(path, data, 0o644)
}

// readJSONMap reads path (if it exists) and parses it as jsonc into an
// ordered-agnostic key->raw-value map, reporting separately whether the raw
// bytes contained comments beyond header - the exact bytes oak-dev's own
// last write would have started the file with - that stripJSONC is about to
// discard. header lets an untouched, previously oak-dev-written file report
// no comments of its own: its header line is a jsonc comment too, so without
// this a round trip through Install (or a check before Uninstall deletes it)
// would always see "comments" that were only ever oak-dev's, not the user's.
// A missing file parses as an empty map, not an error - that's simply
// "nothing to merge with yet".
func readJSONMap(path, header string) (map[string]json.RawMessage, bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]json.RawMessage{}, false, nil
		}
		return nil, false, err
	}
	// One stripComments pass serves both hasComments (a length check) and the
	// jsonc-to-JSON conversion below - calling hasComments(data) here too
	// would otherwise strip comments from the same bytes a second time for no
	// reason.
	withoutComments := stripComments(data)
	hadComments := len(withoutComments) != len(data)
	if hadComments {
		rest := bytes.TrimPrefix(data, []byte(header))
		hadComments = len(stripComments(rest)) != len(rest)
	}
	m := map[string]json.RawMessage{}
	if err := json.Unmarshal(stripTrailingCommas(withoutComments), &m); err != nil {
		return nil, false, fmt.Errorf("parsing existing %s: %w", path, err)
	}
	return m, hadComments, nil
}

// readArray decodes m[key] (if present) as a JSON array of raw elements. A
// missing key or a key holding something other than an array is treated as
// empty rather than an error - a launch.json with no "configurations" yet is
// exactly what a from-scratch install starts from.
func readArray(m map[string]json.RawMessage, key string) []json.RawMessage {
	raw, ok := m[key]
	if !ok {
		return nil
	}
	var arr []json.RawMessage
	if err := json.Unmarshal(raw, &arr); err != nil {
		return nil
	}
	return arr
}

// extractKey pulls the named string field (e.g. "name", "label", "id") out
// of a raw JSON object, for recognizing which array elements oak-dev owns.
// A raw element that isn't an object, or has no such field, contributes an
// empty key - never matches an ownership prefix, so it's always treated as
// foreign rather than dropped.
func extractKey(raw json.RawMessage, field string) string {
	var m map[string]json.RawMessage
	if err := json.Unmarshal(raw, &m); err != nil {
		return ""
	}
	var s string
	if err := json.Unmarshal(m[field], &s); err != nil {
		return ""
	}
	return s
}

// mergeArray drops every element of existing whose field value carries
// prefix (oak-dev's own, superseded by fresh output) and appends generated
// after everything foreign, in generator order - so the generated block is
// always in the same order run to run, which is what makes Install
// idempotent under a byte comparison.
func mergeArray(existing []json.RawMessage, field, prefix string, generated []entry) []json.RawMessage {
	out := make([]json.RawMessage, 0, len(existing)+len(generated))
	for _, raw := range existing {
		if strings.HasPrefix(extractKey(raw, field), prefix) {
			continue
		}
		out = append(out, raw)
	}
	for _, e := range generated {
		out = append(out, e.data)
	}
	return out
}

func rawArray(arr []json.RawMessage) json.RawMessage {
	if arr == nil {
		arr = []json.RawMessage{}
	}
	data, err := json.Marshal(arr)
	if err != nil {
		panic(fmt.Sprintf("oak-dev/internal/vscode: marshaling array: %v", err))
	}
	return data
}

const launchHeader = `// Generated by ` + "`oak-dev vscode install`" + ` - edit oak-dev.yaml or the
// component registry (internal/components), not this file directly.
// Configurations whose "name" starts with "oak-dev: " are regenerated and
// overwritten on every run; anything else you add here is left alone.
//
// Go (Delve, dlv-dap): no path mapping needed. The binary is cross-compiled
// on this host (see internal/build), so its debug info already embeds this
// machine's absolute source paths even though it runs inside a linux
// container - there is no remote host to substitute paths for.
//
// Python (debugpy): pathMappings point at OAKESTRA_REPO/OAKESTRA_NET_REPO as
// this checkout's oak-dev.yaml/.env actually resolve them (see
// ` + "`oak-dev config`" + `), not a hardcoded ../oakestra. justMyCode is false so a
// breakpoint in the shared Oakestra Python libraries (installed from
// LIB_BRANCH at image build time) binds too, not just this component's own
// source.
//
// Each configuration's preLaunchTask runs ` + "`oak-dev debug <component> --wait`" + `,
// so pressing F5 both attaches the debugger and recreates the container with
// it turned on first - no separate terminal step.
`

const tasksHeader = `// Generated by ` + "`oak-dev vscode install`" + ` - edit oak-dev.yaml or the
// component registry (internal/components), not this file directly. Tasks
// whose "label" starts with "oak-dev: ", and inputs whose "id" starts with
// "oakDev", are regenerated and overwritten on every run; anything else you
// add here is left alone.
//
// The hidden "oak-dev: debug <component>" tasks aren't meant to be run from
// the Run Task picker - each exists only as the preLaunchTask a matching
// launch.json configuration runs before attaching.
`

// mergeLaunch reads launchPath (if present), replaces oak-dev's own
// configurations with generatedConfigs, and returns the rendered file.
func mergeLaunch(launchPath string, generatedConfigs []entry) ([]byte, bool, error) {
	m, hadComments, err := readJSONMap(launchPath, launchHeader)
	if err != nil {
		return nil, false, err
	}
	existing := readArray(m, "configurations")
	m["configurations"] = rawArray(mergeArray(existing, "name", launchPrefix, generatedConfigs))
	m["version"] = mustJSON(launchVersion)

	doc, err := writeDoc(launchHeader, m, []string{"version", "configurations"})
	return doc, hadComments, err
}

// mergeTasks is mergeLaunch's counterpart for tasks.json, which additionally
// carries an "inputs" array oak-dev partially owns (ids prefixed oakDev).
func mergeTasks(tasksPath string, generatedTasks, generatedInputs []entry) ([]byte, bool, error) {
	m, hadComments, err := readJSONMap(tasksPath, tasksHeader)
	if err != nil {
		return nil, false, err
	}
	existingTasks := readArray(m, "tasks")
	m["tasks"] = rawArray(mergeArray(existingTasks, "label", taskPrefix, generatedTasks))
	existingInputs := readArray(m, "inputs")
	m["inputs"] = rawArray(mergeArray(existingInputs, "id", inputPrefix, generatedInputs))
	m["version"] = mustJSON(tasksVersion)

	doc, err := writeDoc(tasksHeader, m, []string{"version", "tasks", "inputs"})
	return doc, hadComments, err
}

// writeDoc renders m as jsonc: header (already newline-terminated comment
// lines) followed by a pretty-printed object. Keys in order are emitted
// first, in that order; anything else in m follows, sorted, so the file
// reads the same way from one run to the next instead of shuffling with Go's
// randomized map iteration.
func writeDoc(header string, m map[string]json.RawMessage, order []string) ([]byte, error) {
	var compact bytes.Buffer
	compact.WriteByte('{')
	first := true
	emit := func(key string) error {
		val, ok := m[key]
		if !ok {
			return nil
		}
		if !first {
			compact.WriteByte(',')
		}
		first = false
		keyJSON, err := json.Marshal(key)
		if err != nil {
			return err
		}
		compact.Write(keyJSON)
		compact.WriteByte(':')
		compact.Write(val)
		return nil
	}

	seen := make(map[string]bool, len(order))
	for _, k := range order {
		if err := emit(k); err != nil {
			return nil, err
		}
		seen[k] = true
	}
	var rest []string
	for k := range m {
		if !seen[k] {
			rest = append(rest, k)
		}
	}
	sort.Strings(rest)
	for _, k := range rest {
		if err := emit(k); err != nil {
			return nil, err
		}
	}
	compact.WriteByte('}')

	var pretty bytes.Buffer
	if err := json.Indent(&pretty, compact.Bytes(), "", "  "); err != nil {
		return nil, err
	}
	pretty.WriteByte('\n')

	out := make([]byte, 0, len(header)+pretty.Len())
	out = append(out, header...)
	out = append(out, pretty.Bytes()...)
	return out, nil
}

// uninstallLaunch strips oak-dev's own configurations from launchPath,
// deleting the file if nothing but an empty skeleton would be left.
func uninstallLaunch(launchPath string) (UninstallFileResult, error) {
	res := UninstallFileResult{Path: launchPath}
	if !exists(launchPath) {
		return res, nil
	}
	res.Found = true
	m, hadComments, err := readJSONMap(launchPath, launchHeader)
	if err != nil {
		return res, err
	}
	res.HadComments = hadComments
	kept := stripOwned(readArray(m, "configurations"), "name", launchPrefix)
	// A file that had comments is never deleted outright, even when nothing
	// but oak-dev's own entries and the bare skeleton survive: readJSONMap's
	// jsonc parse already discarded them from m, so a comment is exactly the
	// kind of foreign content onlyKeys can't see - deleting here would erase
	// it with no trace and no warning.
	if len(kept) == 0 && !hadComments && onlyKeys(m, "version", "configurations") {
		res.Removed = true
		return res, removeIfExists(launchPath)
	}
	m["configurations"] = rawArray(kept)
	m["version"] = mustJSON(launchVersion)
	doc, err := writeDoc(launchHeader, m, []string{"version", "configurations"})
	if err != nil {
		return res, err
	}
	return res, os.WriteFile(launchPath, doc, 0o644)
}

// uninstallTasks is uninstallLaunch's counterpart for tasks.json. The file is
// only deleted once both the tasks and inputs arrays are empty of foreign
// content - a tasks.json with a surviving hand-written task but no surviving
// input (or vice versa) still has to stick around - and, as in
// uninstallLaunch, never when the file had comments onlyKeys can't see.
func uninstallTasks(tasksPath string) (UninstallFileResult, error) {
	res := UninstallFileResult{Path: tasksPath}
	if !exists(tasksPath) {
		return res, nil
	}
	res.Found = true
	m, hadComments, err := readJSONMap(tasksPath, tasksHeader)
	if err != nil {
		return res, err
	}
	res.HadComments = hadComments
	keptTasks := stripOwned(readArray(m, "tasks"), "label", taskPrefix)
	keptInputs := stripOwned(readArray(m, "inputs"), "id", inputPrefix)
	if len(keptTasks) == 0 && len(keptInputs) == 0 && !hadComments && onlyKeys(m, "version", "tasks", "inputs") {
		res.Removed = true
		return res, removeIfExists(tasksPath)
	}
	m["tasks"] = rawArray(keptTasks)
	m["inputs"] = rawArray(keptInputs)
	m["version"] = mustJSON(tasksVersion)
	doc, err := writeDoc(tasksHeader, m, []string{"version", "tasks", "inputs"})
	if err != nil {
		return res, err
	}
	return res, os.WriteFile(tasksPath, doc, 0o644)
}

// onlyKeys reports whether m has no keys other than the ones listed. Used to
// decide whether a file, once oak-dev's own array entries are stripped away,
// holds nothing but the bare skeleton oak-dev itself would have written (safe
// to delete outright) or still carries a foreign top-level key - a
// hand-written "compounds" section in launch.json, say - that must not be
// silently discarded along with the file just because "configurations"
// itself happened to contain nothing but oak-dev's own entries.
func onlyKeys(m map[string]json.RawMessage, keys ...string) bool {
	allowed := make(map[string]bool, len(keys))
	for _, k := range keys {
		allowed[k] = true
	}
	for k := range m {
		if !allowed[k] {
			return false
		}
	}
	return true
}

func stripOwned(arr []json.RawMessage, field, prefix string) []json.RawMessage {
	out := make([]json.RawMessage, 0, len(arr))
	for _, raw := range arr {
		if strings.HasPrefix(extractKey(raw, field), prefix) {
			continue
		}
		out = append(out, raw)
	}
	return out
}

func removeIfExists(path string) error {
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
